### ISSUE TITLE
data format

### ISSUE THREAD

**Issue by Kimpaul0517** [chaeyeongyun/WRA-Net#2]
Dear Sir,

Thank you for great work. I had downloaded your dataset, but it is not in the same format as yours. It missed the target folder, which leads to an AssertionError "input image and target image are not matched".Could you please tell me how to solve it？

Best Wishes,

**Comment by chaeyeongyun** [comment]
Thank you for your interest in my work.
There are only motion blurred images in my dataset. You can download target images from original dataset :)
